export default function TermsPage() {
  return (
    <div className="landing-container" style={{ padding: '80px 20px', maxWidth: '800px', margin: '0 auto', color: '#e0e0e8' }}>
      <h1 className="landing-h2" style={{ marginBottom: '40px' }}>Terms of Service</h1>
      <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', lineHeight: '1.6' }}>
        <p>Last updated: 22 March 2026</p>
        
        <h2>1. Introduction</h2>
        <p>Welcome to CinaTech. By accessing or using our service, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.</p>
        
        <h2>2. Service Description</h2>
        <p>CinaTech provides AI-powered strategic analysis reports for marketing agencies. Users upload client onboarding materials, and we generate competitive, regulatory, and strategic insights.</p>
        
        <h2>3. User Obligations</h2>
        <p>You must ensure that you have the legal right and necessary permissions to share any client documents or data you upload to CinaTech. You agree to redact any highly sensitive personal identifiable information before uploading documents to our platform. You are responsible for maintaining the confidentiality of your account.</p>
        
        <h2>4. Data and Privacy</h2>
        <p>Your privacy is important to us. Our collection and use of personal data in connection with the service is described in our Privacy Policy. By using the service, you consent to our data practices as outlined therein.</p>
        
        <h2>5. Intellectual Property</h2>
        <p>The original reports generated by CinaTech for your clients become your property upon generation. However, the underlying AI models, website design, trademarks, and codebase remain the exclusive intellectual property of CinaTech and its licensors.</p>
        
        <h2>6. Limitation of Liability</h2>
        <p>CinaTech provides strategic analysis based on provided inputs and AI interpretation. The reports are advisory in nature. We shall not be held liable for any direct, indirect, incidental, or consequential damages resulting from business decisions made based on our reports.</p>
        
        <h2>7. Governing Law</h2>
        <p>These terms shall be governed and construed in accordance with the laws of England and Wales, without regard to its conflict of law provisions.</p>
        
        <h2>8. Changes to Terms</h2>
        <p>We reserve the right to modify or replace these terms at any time. We will provide notice of any material changes by posting the new terms on this site.</p>
        
        <h2>9. Contact Us</h2>
        <p>If you have any questions about these Terms, please contact us at joseph@cinatech.ai.</p>
      </div>
    </div>
  );
}
