export default function TermsPage() {
  return (
    <div className="landing-container" style={{ padding: '80px 20px', maxWidth: '800px', margin: '0 auto', color: '#e0e0e8' }}>
      <h1 className="landing-h2" style={{ marginBottom: '40px' }}>Terms of Service</h1>
      <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', lineHeight: '1.6' }}>
        <p>Last updated: 22 March 2026</p>
        
        <h2>1. Introduction</h2>
        <p>Welcome to CinaTech. By accessing or using our service, creating an account, or purchasing a plan, you agree to be bound by these Terms of Service. You represent that you are at least 18 years of age and are using the service on behalf of a business entity. CinaTech is exclusively a business-to-business (B2B) service. If you disagree with any part of the terms, you must not access the service.</p>
        
        <h2>2. Service Description and AI Processing</h2>
        <p>CinaTech provides AI-powered strategic analysis reports for marketing agencies. Users upload client onboarding materials, and we generate competitive, regulatory, and strategic insights. You acknowledge that our service utilises third-party artificial intelligence providers, specifically the Anthropic API, to process data and generate these reports. AI-generated advisory content should always be reviewed by a human professional.</p>
        
        <h2>3. User Obligations</h2>
        <p>You must ensure that you have the legal right and necessary permissions to share any client documents or data you upload to CinaTech. You agree to redact any highly sensitive personal identifiable information before uploading documents to our platform. You are responsible for maintaining the confidentiality of your account.</p>
        
        <h2>4. Data, Privacy, and Retention</h2>
        <p>Your privacy is important to us. Our collection and use of personal data in connection with the service is described in our Privacy Policy. By using the service, you consent to our data practices. To ensure data security, we automatically delete uploaded client documents from our active servers 30 days after a report is generated, unless you request early deletion or delete them manually from your dashboard.</p>
        
        <h2>5. Payment, Refunds, and Cancellation</h2>
        <p>CinaTech offers paid services including one-off reports and monthly subscriptions. Due to the computationally intensive and bespoke nature of AI-generated reports, all payments for generated reports are strictly non-refundable once the analysis has commenced. Monthly subscriptions can be cancelled at any time through your account settings; cancellation will take effect at the end of your current billing cycle, and no partial refunds will be provided for unused time.</p>
        
        <h2>6. Intellectual Property</h2>
        <p>The original reports generated by CinaTech for your clients become your property upon generation. However, the underlying AI models, website design, trademarks, and codebase remain the exclusive intellectual property of CinaTech and its licensors.</p>
        
        <h2>7. Limitation of Liability</h2>
        <p>CinaTech provides strategic analysis based on provided inputs and AI interpretation. The reports are advisory in nature. We shall not be held liable for any direct, indirect, incidental, or consequential damages resulting from business decisions made based on our reports.</p>
        
        <h2>8. Governing Law and International Use</h2>
        <p>These terms shall be governed and construed in accordance with the laws of England and Wales, without regard to its conflict of law provisions. If you access the service from outside the United Kingdom, you are responsible for compliance with all local laws and regulations governing data usage and software access in your jurisdiction.</p>
        
        <h2>9. Indemnification</h2>
        <p>You agree to defend, indemnify, and hold harmless CinaTech, its affiliates, and their respective directors, officers, employees, and agents from and against any claims, actions, or demands, including reasonable legal and accounting fees, alleged to result from your use of the service or your breach of these Terms of Service.</p>
        
        <h2>10. Severability</h2>
        <p>If any provision of these Terms is found to be unenforceable or invalid under any applicable law, such unenforceability or invalidity shall not render these Terms unenforceable or invalid as a whole, and such provisions shall be deleted without affecting the remaining provisions herein.</p>

        <h2>11. Changes to Terms</h2>
        <p>We reserve the right to modify or replace these terms at any time. We will provide notice of any material changes by posting the new terms on this site.</p>
        
        <h2>12. Contact Us</h2>
        <p>If you have any questions about these Terms, please contact us at joseph@cinatech.ai.</p>
      </div>
    </div>
  );
}
